/** Every template, one representative URL each. */
export const TEMPLATES = [
  "/",
  "/church/esocs",
  "/church/esocs/leaders",
  "/church/cmc-9",
  "/church/rumuomasi-province",
  "/church/oroigwe-pro-cathedral",
  "/church/women",
  "/church/youth",
  "/church/directorate-of-finance",
  "/find",
  "/structure",
  "/sections",
  "/history",
  "/leaders",
  "/leaders/moses-orimolade-tunolase",
  "/tours",
  "/tours/pastoral-visits-2023",
  "/ordinations",
  "/glossary",
  "/events",
  "/events/easter-sunday-2027",
  "/calendar",
  "/news",
  "/posts/dedication-2022-08-13-dedication-of-diobu-provincial-headquarters",
  "/media",
  "/media/albums/100th-anniversary-celebration",
  "/give",
  "/prayer",
  "/contact",
  "/search?q=ibadan",
] as const;
